### ISSUE TITLE
css "error" in submenu. Menu text turns white on white when using smal devices

### ISSUE THREAD

**Issue by poul-erik** [ChrisHammond/HammerHead#2]
Hi Chris,

First thank you for all your work on templates. I have used them all with success. I maintain a DNN website (the DNN stuff not the content) and the users (a non profit community) would like to have a more responsive layout, so I convinced them to try HammerHead. Every thing looks good except for the submenus, they turn white on white. I have struggled with it for some time and finally I jumped to your site: https://www.chrishammond.com/ to see if I could find out how you did. Just to find out you have the same issue.

![billede](https://user-images.githubusercontent.com/38832672/39405622-8525791c-4ba8-11e8-9aac-3cc9d4609ab0.png)

Due you have any idea of what is happening. I have looked at the css files over and over again without finding anything.

Best regards

Poul Erik

**Comment by ChrisHammond** [comment]
This should be an easy fix, I'll work on something tonight

**Comment by ChrisHammond** [comment]
Fixed with the 01.00.01 release

**Comment by poul-erik** [comment]
Thank you
