### ISSUE TITLE
Install on Evoq 8.5.0?

### ISSUE THREAD

**Issue by JaySMa** [ChrisHammond/HammerHead#3]
Is it possible to install this on Evoq 8.5.0?

It says that 9.0.2 is the minimal installation, but can this be tricked?

Thanks..

**Comment by ChrisHammond** [comment]
I honestly don't know, probably can. Just start by modifying the .DNN file to a lower version number, that'll likely do the trick. 

Put the edited file back in the ZIP file then upload.

**Comment by JaySMa** [comment]
I edited the HammerHead.DNN file and in the two dependancy entries, changed them to 8.0.0.  The skin was then able to be installed.

Will run through it on development and see if there's any issues, but I don't really think there will be.

Thank you..

**Comment by ChrisHammond** [comment]
Thanks for the followup
